spring:
  application:
    name: Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/souravkhurpe/Rating-Portal-Config-Server-Microservice
          clone-on-start: true
server:
  port: 1011